# This workflow will build a Kotlin/Gradle project

name: yamul-backend-ci

on:
  push:
    branches: [ "main" ]
    paths:
      - 'yamul-backend/**'
      - 'api-definitions/**'
      - '.github/workflows/yamul-backend-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'yamul-backend/**'
      - 'api-definitions/**'
      - '.github/workflows/yamul-backend-ci.yml'

jobs:

  build:
    defaults:
      run:
        working-directory: ./yamul-backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:                                  
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Setup execution permissions for gradlew
      run: chmod +x ./gradlew

    - name: Get MUL files cache key
      id: mul-cache-key
      working-directory: ${{ github.workspace }}
      run: echo "sha=$(git ls-remote https://cavefish:${{ secrets.PAT }}@github.com/${{ secrets.MUL_FILES_REPO_URL }} HEAD | cut -f1)" >> $GITHUB_OUTPUT

    - name: Cache MUL files
      id: cache-mul-files
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/uo-server-mul-files
        key: mul-files-${{ steps.mul-cache-key.outputs.sha }}

    - name: Clone MUL files
      if: steps.cache-mul-files.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}
      run: git clone --depth=1 https://cavefish:${{ secrets.PAT }}@github.com/${{ secrets.MUL_FILES_REPO_URL }}.git uo-server-mul-files

    - name: Pull latest MUL files
      if: steps.cache-mul-files.outputs.cache-hit == 'true'
      working-directory: ${{ github.workspace }}/uo-server-mul-files
      run: git pull

    - name: Build
      run: ./gradlew assemble -x googleJavaFormat -x verifyGoogleJavaFormat

    - name: Test
      run: ./gradlew test
      env:
        MULTIMA_MULFILES_DIR: ${{ github.workspace }}/uo-server-mul-files
